[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[variables]
NODE_VERSION = "20.19.0"

[deploy]
startCommand = "npm run preview"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
VITE_APP_NAME = "TOIT Nexus"
VITE_APP_VERSION = "1.0.0"