# Configuração do Railway para TOIT NEXUS
# Este arquivo configura a implantação do projeto no Railway

[build]
  # Comandos de build para o frontend e backend
  builder = "npx -y @railway/cli@latest up --service toit-nexus --detach"
  buildCommand = "cd client && npm install && npm run build"
  
  # Pasta de saída do frontend
  outputDirectory = "client/dist"

[deploy]
  # Domínios personalizados
  [[deploy.custom_domains]]
    name = "nexus.toit.com.br"
  
  [[deploy.custom_domains]]
    name = "supnexus.toit.com.br"

# Configurações do banco de dados
[database]
  # Usa o plugin do PostgreSQL do Railway
  plugin = "postgresql"

# Variáveis de ambiente compartilhadas
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.x"

# Configurações específicas para o frontend
[[services]]
  name = "toit-nexus-frontend"
  root = "./client"
  
  [services.build]
    command = "npm install && npm run build"
    publish = "./dist"
  
  [services.start]
    command = "npm run preview -- --host"
    port = 3000
  
  [services.environment]
    VITE_API_URL = "https://toit-nexus-backend.up.railway.app/api"
    NODE_ENV = "production"

# Configurações específicas para o backend
[[services]]
  name = "toit-nexus-backend"
  root = "./server"
  
  [services.build]
    command = "npm install"
  
  [services.start]
    command = "npm start"
    port = 3001
  
  [services.environment]
    NODE_ENV = "production"
    PORT = "3001"
    DATABASE_URL = "${{toit-nexus-db.DATABASE_URL}}"
