# Configuração do Railway para TOIT NEXUS
# Este arquivo configura a implantação do projeto no Railway

[build]
  # Usa o nixpacks como builder padrão
  builder = "nixpacks"
  
  # Comandos para instalar dependências e fazer build
  buildCommand = "npm install && cd client && npm install && npm run build && cd ../server && npm install && npm run build"
  
  # Pasta de saída do build
  outputDirectory = "client/dist"
  
  # Comando para iniciar o servidor
  startCommand = "node railway-frontend.js"

# Configuração do banco de dados PostgreSQL
[database]
  plugin = "postgresql"
  version = "14"

# Variáveis de ambiente globais
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.x"
  PORT = "3000"

# NOTA: Os domínios personalizados devem ser configurados diretamente no painel do Railway
# sob as configurações de domínio do projeto.
